### ISSUE TITLE
Add visibility for authors

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/sul_pub#1251]
When retrieving author information from CAP, also store visibility.

This will require:
* Adding column for storing CAP visibility to author model
* Enhancing Author Poller to store CAP visibility

**Comment by peetucket** [comment]
See discussions in slack for updates: 

https://stanfordlib.slack.com/archives/C0T8CJD3L/p1620945545013300
and 
https://stanfordlib.slack.com/archives/C0T8CJD3L/p1620933705006200

Bottom line: expectation is that the controlled vocabulary is ok, and we should not get nils back, but we will have nils in our database because we have all authors for all time, while their API only returns authors currently at Stanford.  Still some discussion on what is coming back from their API endpoint.

**Comment by peetucket** [comment]
slack channel indicates we should be getting all visibilities back

Checking on UAT where the script was run to populate seems to confirm this:

```
MariaDB [sul-pub]> select cap_visibility,count(*) as count from authors group by cap_visibility order by count desc;
+----------------+--------+
| cap_visibility | count  |
+----------------+--------+
| NULL           | 100390 |
| public         |  22492 |
| stanford       |  14254 |
| private        |    669 |
+----------------+--------+
```
