### ISSUE TITLE
Determine the publications that were harvested from ScienceWire that do no have WoS ID

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#217]
When we harvest from Web of Science, we need to match against existing known publications that were harvested from ScienceWire to be sure we do not introduce duplicated publications.  In other to do this, we need to use WoS IDs to match against existing publications.  We need to

- [x] catalog all existing publications to see which ones have WoS IDs
- [x] see if we can get WoS IDs for those existing publications and update our system

There may already be code to do this or it may have already been done.

**Comment by darrenleeweber** [comment]
We discussed trying to identify the existing records that do or do not have a WoS-ID.  We have a script related to this issue, see
- https://github.com/sul-dlss/sul_pub/blob/master/script/missing_wos_ids.rb

We discussed asking TR to provide a WoS-ID for any existing records that do not have one.  This would allow us to de-dup existing records against new records and, possibly, decide how we might deprecate, replace and/or migrate existing records to the new records.

**Comment by darrenleeweber** [comment]
https://github.com/sul-dlss/sul_pub/wiki/Useful-Rails-runner-scripties

**Comment by darrenleeweber** [comment]
Some prod-db numbers:
```ruby
> SciencewireSourceRecord.count
=> 394138
```

**Comment by darrenleeweber** [comment]
Linking `Publication` to `SciencewireSourceRecord` identifiers
```ruby
Publication.select(:id, :sciencewire_id, :pmid).limit(10)
```

**Comment by peetucket** [comment]
So does it follow that there are 61,257 Sciencewire Source records that do *not* have WoS IDs?
 i.e. total number of SciencewireSourceRecords (394138) minus total number of items with a WosID (332881)

So those 61,257 records potentially cannot be matched against records coming from the new API.

**Comment by darrenleeweber** [comment]
We also have PMID and some of the new WoS-UID values are MEDLINE-IDs that might match up with the PMID.  I think this issue was about updating the existing records to get as many WoS-IDs as possible and that's done.  Also, this issue is about how to find pubs with a WoS-ID (or PMID) and that's done.  I think we need new issues for analysis and implementation of how we match new SOAP-API records with any existing records we already have (no matter where they came from).  We have issues already for this kind of task, so I think we tackle the rest of this in those issues.
