### ISSUE TITLE
Analysis: how to match up new WoS records with existing Sciencewire records so we do not create duplicates?

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#260]
Proposal:

- [ ]  fetch records for a given author via WoS API
- [ ]  for each record, look at identifiers in the following order provided (WoSID, Pu medID, DOI) in the result, and then try and locate an existing Publication with that identifier in the PublicationIdentifier table
- [ ]  if the publication is found, add any missing identifiers to PublicationIdentifier table for that publication from the WoS record (e.g. DOI, PMID, etc.)
- [ ] if the publication is not found, add it as a new publication via usual methods and build new pub hash

Note, we may still be generating dupes because our existing identifier information may be incomplete (e.g. we may already have the publication identifier in the WoS result but may be missing its WoS or PMID).

Work here should ensure our WoS IDs are for as up to date as they can be for Sciencewire results: #217

Informed by the work in #285 and #265

**Comment by atz** [comment]
#261 documents the gaps in matching via `publication_identifiers` table.  

When we get back:
```xml
<uid>WOS:A1991GP84100006<uid>
<uid>MEDLINE:24303232<uid>
``` 

We can match those to `publication_identifiers WHERE identifier_type = 'WoSItemID'` (or `PMID`, respectively).  4725 of our PMIDs don't have ScienceWire IDs, however, so those are documents we already know about, but don't know *enough* about.

### DUPS
Additionally, here's the number of duplicate identifier values per type in our `publication_identifiers` table:
```
doi: 4010
isbn: 19
legacy_cap_pub_id: 0
pmc: 33
PMID: 635
PublicationItemID: 24
SULPubId: 0
WoSItemID: 13
```

Literally any ID type we didn't coin ourselves has dups.  This should have been prevented at the database level.  We already have an index over `["identifier_type", "identifier_value"]`, but it should have been made unique. 

### NULL ENTRIES

Additionally, we have null `identifier_value` fields for **1606** `doi` records (and **1845** `isbn` records).  Those entries should probably be deleted since they don't identify anything!  `identifier_value` should be required in the ActiveRecord model AND enforced at the DB level.

**Comment by darrenleeweber** [comment]
For the `DOI`, there are two fields for storing the values and either or both of them might be populated; see #241 & #246 for related work.

**Comment by atz** [comment]
@darrenleeweber Are you saying the DOI value is only sometimes stored in `publication_identifiers.identifier_uri`?  That seems frustrating.

Breakdown of publication_identifier DOIs (on cap-qa):
- 168828 total
- 153107 `.where("identifier_value = identifier_uri")`
- 13893 `.where("identifier_value != identifier_uri")`
- 334 where uri is NULL
  - 222 still have a value
  - 112 value is NULL also

If I repeat the analysis looking for uniqueness of URIs, I find dups on that field, too:
```
doi: 2244 (334 null)
PMID: 635
WoSItemID: 13
```

**Comment by darrenleeweber** [comment]
I'm doing some work to try to clean up DOIs in https://github.com/sul-dlss/sul_pub/issues/241 and https://github.com/sul-dlss/sul_pub/pull/246
