### ISSUE TITLE
Add identifier fields to WebOfScienceRecord model/db

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#395]
This is because the WoS source record will not have all identifiers, which need to be fetched via the LinksAMR API.  These columns provide a location to store the additional identifiers pulled from the LinksAMR API.

Fields:
* pmid
* doi

- [ ] create a migration to add pmid and doi columns to the WebofScience source record table
- [ ] create helper methods in WoS source record to extract those identifiers from the source record
- [ ] save identifiers in the sourcerecord table

**Comment by darrenleeweber** [comment]
- [x] create a migration to add pmid and doi columns to the WebofScience source record table
- [ ] create helper methods in WoS source record to extract those identifiers from the source record
  - can't be done because the identifiers are not always there
- [ ] save identifiers in the sourcerecord table
  - out of scope for this ticket, but should be a part of harvesting
