### ISSUE TITLE
Update publication API to use WoS client for searching by DOI

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#603]
The "sourcelookup" method in the publications controller currently uses the ScienceWire client to search by DOI (by making a call to the DoiSearch class).  
- [x] update DoiSearch class to use the Web of Science client instead
- [x] removal/updating of sources param in sourcelookup
- [ ] compare return structure from WoS API with return structure from sciencewire API for compatibility

**Comment by darrenleeweber** [comment]
If there is no author, only a DOI, use the query method, see
- https://github.com/sul-dlss/sul_pub/blob/master/lib/web_of_science/queries.rb#L81
- `WebOfScience.queries.search_by_doi(doi)`
- note that the WOS-API can return funky results for DOI because they do partial string matching
  - the queries.search_by_doi will only return the first result
  - there is an open issue to look into changing that behavior to return the top 10 hits or something

If there is an author to associate with a DOI, use the harvester method, see
- https://github.com/sul-dlss/sul_pub/blob/master/lib/web_of_science/harvester.rb#L34
- WebOfScience.harvester.process_dois(author, dois)
  - it might return an empty array if the DOIs are already in the PublicationIdentifiers
    - in that case, find or create the author contribution for the existing Publication
    - assuming the harvest will only be called after checking for existing pub anyway
