### ISSUE TITLE
WOS harvest efficiency

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/sul_pub#673]
Suggestions for improving the efficiency of WOS harvests

**Comment by darrenleeweber** [comment]
## Use background jobs (e.g. use REDIS) for Author harvests

### Serial, batch retrieval from WOS API

- Run an author query to get back WOS-UIDs
  - get all the WOS-Links identifiers for all the UIDs
  - remove any UIDs that can be matched to author-contributions via PublicationIdentifiers
  - when matching PublicationIdentifiers - use only identifiers: UID, DOI, PMID (others?)
- For all UIDs that do not match any contributions
  - retrieve the full records and save them to a key:value store (REDIS)
  - use the author-id + the UID as a compound key
  - store the UID full record XML as the value
  - include the Links-API identifiers in there too
  - consider various alternatives for the key:value details

### Concurrent integration into the sul_pub database
- Run concurrent processes that consume from the REDIS key:value store
  - these concurrent processes should have no HTTP requests
    - they should never hit the WOS-API or the Links-API
    - one exception - they might need to queue or spawn some PubMed integration
 - retrieve any author-UID:xml (key:value) data and process it
   - see `WebOfScience::ProcessRecords`
   - refactor  `WebOfScience::ProcessRecords` to create `WebOfScience::ProcessRecord`
- once an author:UID record is processed, remove it from the queue (key:value store)
  - or consider keeping some cached data available for a short period of time?
  - a cache might be useful, because not all of the retrieved records are stored in the sul_pub db
  - this depends on whether a WOS-src-record is saved even if it matches existing publication data

**Comment by atz** [comment]
I'm proceeding under the assumption of zero architectural revisions.  

### `ProcessRecords` 
- does (up to) 4 queries on the same table that could be done in one query, [here](https://github.com/sul-dlss/sul_pub/blob/master/lib/web_of_science/process_records.rb#L75-L78).

### `WebOfScience::Contributions` 
is full of anti-patterns.  `#create_contribution` does:
```ruby
contrib.save!
...
contrib.publication.pubhash_needs_update!
contrib.publication.save!
```
The initial save is unnecessary since `Publication` has an autosave on its associated objects.  

`#publication_identifier` does:
```ruby
 pub_ids = PublicationIdentifier.where(identifier_type: type, identifier_value: value)
 pub_ids.empty? ? nil : pub_ids.first
```
Why are we **still** fighting the `.where(...).first` pattern?  Returning `nil` or one object is EXACTLY what `.find_by` does.  

`#find_or_create_contribution` does `find_or_initialize_by` and then hands off for the double save mentioned above.  It could just do `find_or_create_by!` with a block, then `create_contribution` can be removed.

`#contribution_by_identifier?` looks like an interrogative, but is actually responsible for creating records.  It does: 
```ruby
contrib = find_or_create_contribution(author, pub_id.publication)
contrib.persisted?
```
This is an unnecessary check since the point of any `find_or_create_` statement is that it returns nil or one persisted object. 

I will try to submit a PR to address some of these points.

**Comment by atz** [comment]
Another copy-pasta 4x query that could be one, and is identical to the previous one, [here](https://github.com/sul-dlss/sul_pub/blob/master/lib/web_of_science/process_record.rb#L71-L74)
```ruby
        contribution_by_identifier?(author, 'WosUID', record.uid) ||
          contribution_by_identifier?(author, 'WosItemID', record.wos_item_id) ||
          contribution_by_identifier?(author, 'doi', record.doi) ||
          contribution_by_identifier?(author, 'pmid', record.pmid)
```
