### ISSUE TITLE
Investigate process by which publications are created to be sure a new publication is added if needed

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#751]
A call to the authorship API (app/api/sul_bib/authorship_api.rb#POST) with a pmid, sw_id or wos_uid should end up creating the publication as well as the contribution, if the publication does not yet exist.  This is because the call may result as a user searches for a publication via DOI, Title or PMID and this publication may not yet exist in our database when they ask for it to be added.

It's not clear this will actually happen for wos_uid and the profiles team claims it isn't working

**Comment by peetucket** [comment]
Following the logic, e.g. for WoS, leads to a call to `get_publication_via_wos` which ultimately leads to `uids = WebOfScience.harvester.process_uids(author, [wos_uid])` if the publication cannot be found by wos_uid.  This `process_uids` method in the web of science harvester calls `author_contributions` in the `WebOfScience::Contributions` module which then seems to just look for existing publications (not creating them if needed).  Its unclear where in this chain a new publication would be created if needed.

**Comment by atz** [comment]
- `process_uids` ends by calling `process_records author, queries.retrieve_by_id(uids)`
- `process_records` relies on `WebOfScience::ProcessRecords#execute`
- `execute` calls `create_publications` which calls (indirectly): 
  - `WebOfScienceSourceRecord.create!`,
  - `Publication.create!`, and
  - `find_or_create_contribution` from `WebOfScience::Contributions`

That latter does `publication.contributions.find_or_create_by!` with a block.  So on a summary reading, this codepath definitely can create source records, publications and associated contributions.  Since all those `create` statements are *`!`*, it shouldn't be possible for them to fail quietly. 

 I'll now move on to examining the tests for `find_or_create_contribution`.

**Comment by atz** [comment]
`find_or_create_contribution` is untested.

**Comment by atz** [comment]
But there are tests that confirm `#execute` changes all: 
- `WebOfScienceSourceRecord.count`, 
- `Publication.count`, 
- `PublicationIdentifier.count`, 
- `Contribution.count`

This seems enough to conclude that during expected operation, pubs and contribs are created.  The question now is whether anything unexpected is happening.

**Comment by peetucket** [comment]
Tested the authorship API in cap-dev in two ways, one posting a wos_uid for an existing publication, and the second posting a wos_uid for a publication we don't have it.  It worked as expected in both cases.

IDS tested:

existing (still exists):
`
{"cap_profile_id":"35324","featured":false,"status":"approved","visibility":"PUBLIC","wos_uid":"WOS:000316989200033"}
`
new (now created): 
`{"cap_profile_id":"35324","featured":false,"status":"approved","visibility":"PUBLIC","wos_uid":"WOS:A1951UC27900018"}`

**Comment by atz** [comment]
Improved accuracy and readability of related tests in: #768
